# Generated by Django 2.2 on 2021-07-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_bjh', models.CharField(max_length=16)),
                ('s_xnxq', models.CharField(max_length=16)),
                ('s_schedule', models.TextField()),
            ],
        ),
    ]
